// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE0        = 32'h 40060000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE1        = 32'h 40070000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE2        = 32'h 400b0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE3        = 32'h 400c0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE4        = 32'h 400d0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE5        = 32'h 40110000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN0         = 32'h 40120000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN1         = 32'h 40160000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN2         = 32'h 40170000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN3         = 32'h 40180000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN4         = 32'h 40190000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN5         = 32'h 401a0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN0          = 32'h 401b0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN1          = 32'h 401c0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN2          = 32'h 401d0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN3          = 32'h 401e0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN4          = 32'h 401f0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN0    = 32'h 40200000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN1    = 32'h 40210000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN2    = 32'h 40220000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN3    = 32'h 40230000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN4    = 32'h 40240000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE6        = 32'h 40250000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE7        = 32'h 40260000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_BRIDGE8        = 32'h 40270000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN6         = 32'h 40280000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN7         = 32'h 40290000;
  localparam logic [31:0] ADDR_SPACE_ERGO_SETUP_GEN8         = 32'h 402a0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN5          = 32'h 402b0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_HOLD_GEN6          = 32'h 402c0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN5    = 32'h 402d0000;
  localparam logic [31:0] ADDR_SPACE_ERGO_CDC_HAZARD_GEN6    = 32'h 402e0000;
  localparam logic [31:0] ADDR_SPACE_UART0                   = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_I2C0                    = 32'h 40080000;
  localparam logic [31:0] ADDR_SPACE_GPIO                    = 32'h 40040000;
  localparam logic [31:0] ADDR_SPACE_SPI_DEVICE              = 32'h 40050000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER                = 32'h 40100000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR_AON              = 32'h 40400000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR_AON              = 32'h 40410000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR_AON              = 32'h 40420000;
  localparam logic [31:0] ADDR_SPACE_PINMUX_AON              = 32'h 40460000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__CORE          = 32'h 40130000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__PRIM          = 32'h 40138000;
  localparam logic [31:0] ADDR_SPACE_LC_CTRL                 = 32'h 40140000;
  localparam logic [31:0] ADDR_SPACE_ALERT_HANDLER           = 32'h 40150000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__REGS = 32'h 40500000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__RAM  = 32'h 40600000;
  localparam logic [31:0] ADDR_SPACE_AON_TIMER_AON           = 32'h 40470000;
  localparam logic [31:0] ADDR_SPACE_AST                     = 32'h 40480000;

  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE0        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE1        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE2        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE3        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE4        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE5        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN0         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN1         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN2         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN3         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN4         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN5         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN0          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN1          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN2          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN3          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN4          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN0    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN1    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN2    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN3    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN4    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE6        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE7        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_BRIDGE8        = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN6         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN7         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_SETUP_GEN8         = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN5          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_HOLD_GEN6          = 32'h 00000007;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN5    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_ERGO_CDC_HAZARD_GEN6    = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_UART0                   = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_I2C0                    = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_GPIO                    = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SPI_DEVICE              = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER                = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_PWRMGR_AON              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RSTMGR_AON              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_CLKMGR_AON              = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_PINMUX_AON              = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__CORE          = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__PRIM          = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_LC_CTRL                 = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_ALERT_HANDLER           = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__REGS = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__RAM  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AON_TIMER_AON           = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_AST                     = 32'h 000003ff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 49;

  typedef enum int {
    TlErgoCdcBridge0 = 0,
    TlErgoCdcBridge1 = 1,
    TlErgoCdcBridge2 = 2,
    TlErgoCdcBridge3 = 3,
    TlErgoCdcBridge4 = 4,
    TlErgoCdcBridge5 = 5,
    TlErgoSetupGen0 = 6,
    TlErgoSetupGen1 = 7,
    TlErgoSetupGen2 = 8,
    TlErgoSetupGen3 = 9,
    TlErgoSetupGen4 = 10,
    TlErgoSetupGen5 = 11,
    TlErgoHoldGen0 = 12,
    TlErgoHoldGen1 = 13,
    TlErgoHoldGen2 = 14,
    TlErgoHoldGen3 = 15,
    TlErgoHoldGen4 = 16,
    TlErgoCdcHazardGen0 = 17,
    TlErgoCdcHazardGen1 = 18,
    TlErgoCdcHazardGen2 = 19,
    TlErgoCdcHazardGen3 = 20,
    TlErgoCdcHazardGen4 = 21,
    TlErgoCdcBridge6 = 22,
    TlErgoCdcBridge7 = 23,
    TlErgoCdcBridge8 = 24,
    TlErgoSetupGen6 = 25,
    TlErgoSetupGen7 = 26,
    TlErgoSetupGen8 = 27,
    TlErgoHoldGen5 = 28,
    TlErgoHoldGen6 = 29,
    TlErgoCdcHazardGen5 = 30,
    TlErgoCdcHazardGen6 = 31,
    TlUart0 = 32,
    TlI2C0 = 33,
    TlGpio = 34,
    TlSpiDevice = 35,
    TlRvTimer = 36,
    TlPwrmgrAon = 37,
    TlRstmgrAon = 38,
    TlClkmgrAon = 39,
    TlPinmuxAon = 40,
    TlOtpCtrlCore = 41,
    TlOtpCtrlPrim = 42,
    TlLcCtrl = 43,
    TlAlertHandler = 44,
    TlSramCtrlRetAonRegs = 45,
    TlSramCtrlRetAonRam = 46,
    TlAonTimerAon = 47,
    TlAst = 48
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
