// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// main
//   -> s1n_50
//     -> ergo_cdc_bridge0
//     -> ergo_cdc_bridge1
//     -> ergo_cdc_bridge2
//     -> ergo_cdc_bridge3
//     -> ergo_cdc_bridge4
//     -> ergo_cdc_bridge5
//     -> ergo_setup_gen0
//     -> ergo_setup_gen1
//     -> ergo_setup_gen2
//     -> ergo_setup_gen3
//     -> ergo_setup_gen4
//     -> ergo_setup_gen5
//     -> ergo_hold_gen0
//     -> ergo_hold_gen1
//     -> ergo_hold_gen2
//     -> ergo_hold_gen3
//     -> ergo_hold_gen4
//     -> ergo_cdc_hazard_gen0
//     -> ergo_cdc_hazard_gen1
//     -> ergo_cdc_hazard_gen2
//     -> ergo_cdc_hazard_gen3
//     -> ergo_cdc_hazard_gen4
//     -> ergo_cdc_bridge6
//     -> ergo_cdc_bridge7
//     -> ergo_cdc_bridge8
//     -> ergo_setup_gen6
//     -> ergo_setup_gen7
//     -> ergo_setup_gen8
//     -> ergo_hold_gen5
//     -> ergo_hold_gen6
//     -> ergo_cdc_hazard_gen5
//     -> ergo_cdc_hazard_gen6
//     -> uart0
//     -> i2c0
//     -> gpio
//     -> spi_device
//     -> rv_timer
//     -> pwrmgr_aon
//     -> rstmgr_aon
//     -> clkmgr_aon
//     -> pinmux_aon
//     -> otp_ctrl.core
//     -> otp_ctrl.prim
//     -> lc_ctrl
//     -> alert_handler
//     -> ast
//     -> sram_ctrl_ret_aon.ram
//     -> sram_ctrl_ret_aon.regs
//     -> aon_timer_aon

module xbar_peri (
  input clk_peri_i,
  input rst_peri_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_main_i,
  output tlul_pkg::tl_d2h_t tl_main_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge0_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge0_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge1_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge1_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge2_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge2_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge3_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge3_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge4_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge4_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge5_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge5_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen0_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen0_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen1_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen1_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen2_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen2_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen3_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen3_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen4_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen4_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen5_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen5_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen0_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen0_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen1_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen1_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen2_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen2_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen3_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen3_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen4_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen4_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen0_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen0_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen1_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen1_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen2_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen2_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen3_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen3_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen4_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen4_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge6_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge6_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge7_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge7_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_bridge8_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_bridge8_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen6_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen6_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen7_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen7_i,
  output tlul_pkg::tl_h2d_t tl_ergo_setup_gen8_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_setup_gen8_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen5_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen5_i,
  output tlul_pkg::tl_h2d_t tl_ergo_hold_gen6_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_hold_gen6_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen5_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen5_i,
  output tlul_pkg::tl_h2d_t tl_ergo_cdc_hazard_gen6_o,
  input  tlul_pkg::tl_d2h_t tl_ergo_cdc_hazard_gen6_i,
  output tlul_pkg::tl_h2d_t tl_uart0_o,
  input  tlul_pkg::tl_d2h_t tl_uart0_i,
  output tlul_pkg::tl_h2d_t tl_i2c0_o,
  input  tlul_pkg::tl_d2h_t tl_i2c0_i,
  output tlul_pkg::tl_h2d_t tl_gpio_o,
  input  tlul_pkg::tl_d2h_t tl_gpio_i,
  output tlul_pkg::tl_h2d_t tl_spi_device_o,
  input  tlul_pkg::tl_d2h_t tl_spi_device_i,
  output tlul_pkg::tl_h2d_t tl_rv_timer_o,
  input  tlul_pkg::tl_d2h_t tl_rv_timer_i,
  output tlul_pkg::tl_h2d_t tl_pwrmgr_aon_o,
  input  tlul_pkg::tl_d2h_t tl_pwrmgr_aon_i,
  output tlul_pkg::tl_h2d_t tl_rstmgr_aon_o,
  input  tlul_pkg::tl_d2h_t tl_rstmgr_aon_i,
  output tlul_pkg::tl_h2d_t tl_clkmgr_aon_o,
  input  tlul_pkg::tl_d2h_t tl_clkmgr_aon_i,
  output tlul_pkg::tl_h2d_t tl_pinmux_aon_o,
  input  tlul_pkg::tl_d2h_t tl_pinmux_aon_i,
  output tlul_pkg::tl_h2d_t tl_otp_ctrl__core_o,
  input  tlul_pkg::tl_d2h_t tl_otp_ctrl__core_i,
  output tlul_pkg::tl_h2d_t tl_otp_ctrl__prim_o,
  input  tlul_pkg::tl_d2h_t tl_otp_ctrl__prim_i,
  output tlul_pkg::tl_h2d_t tl_lc_ctrl_o,
  input  tlul_pkg::tl_d2h_t tl_lc_ctrl_i,
  output tlul_pkg::tl_h2d_t tl_alert_handler_o,
  input  tlul_pkg::tl_d2h_t tl_alert_handler_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_ret_aon__regs_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_ret_aon__regs_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_ret_aon__ram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_ret_aon__ram_i,
  output tlul_pkg::tl_h2d_t tl_aon_timer_aon_o,
  input  tlul_pkg::tl_d2h_t tl_aon_timer_aon_i,
  output tlul_pkg::tl_h2d_t tl_ast_o,
  input  tlul_pkg::tl_d2h_t tl_ast_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_peri_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_50_us_h2d ;
  tl_d2h_t tl_s1n_50_us_d2h ;


  tl_h2d_t tl_s1n_50_ds_h2d [49];
  tl_d2h_t tl_s1n_50_ds_d2h [49];

  // Create steering signal
  logic [5:0] dev_sel_s1n_50;



  assign tl_ergo_cdc_bridge0_o = tl_s1n_50_ds_h2d[0];
  assign tl_s1n_50_ds_d2h[0] = tl_ergo_cdc_bridge0_i;

  assign tl_ergo_cdc_bridge1_o = tl_s1n_50_ds_h2d[1];
  assign tl_s1n_50_ds_d2h[1] = tl_ergo_cdc_bridge1_i;

  assign tl_ergo_cdc_bridge2_o = tl_s1n_50_ds_h2d[2];
  assign tl_s1n_50_ds_d2h[2] = tl_ergo_cdc_bridge2_i;

  assign tl_ergo_cdc_bridge3_o = tl_s1n_50_ds_h2d[3];
  assign tl_s1n_50_ds_d2h[3] = tl_ergo_cdc_bridge3_i;

  assign tl_ergo_cdc_bridge4_o = tl_s1n_50_ds_h2d[4];
  assign tl_s1n_50_ds_d2h[4] = tl_ergo_cdc_bridge4_i;

  assign tl_ergo_cdc_bridge5_o = tl_s1n_50_ds_h2d[5];
  assign tl_s1n_50_ds_d2h[5] = tl_ergo_cdc_bridge5_i;

  assign tl_ergo_setup_gen0_o = tl_s1n_50_ds_h2d[6];
  assign tl_s1n_50_ds_d2h[6] = tl_ergo_setup_gen0_i;

  assign tl_ergo_setup_gen1_o = tl_s1n_50_ds_h2d[7];
  assign tl_s1n_50_ds_d2h[7] = tl_ergo_setup_gen1_i;

  assign tl_ergo_setup_gen2_o = tl_s1n_50_ds_h2d[8];
  assign tl_s1n_50_ds_d2h[8] = tl_ergo_setup_gen2_i;

  assign tl_ergo_setup_gen3_o = tl_s1n_50_ds_h2d[9];
  assign tl_s1n_50_ds_d2h[9] = tl_ergo_setup_gen3_i;

  assign tl_ergo_setup_gen4_o = tl_s1n_50_ds_h2d[10];
  assign tl_s1n_50_ds_d2h[10] = tl_ergo_setup_gen4_i;

  assign tl_ergo_setup_gen5_o = tl_s1n_50_ds_h2d[11];
  assign tl_s1n_50_ds_d2h[11] = tl_ergo_setup_gen5_i;

  assign tl_ergo_hold_gen0_o = tl_s1n_50_ds_h2d[12];
  assign tl_s1n_50_ds_d2h[12] = tl_ergo_hold_gen0_i;

  assign tl_ergo_hold_gen1_o = tl_s1n_50_ds_h2d[13];
  assign tl_s1n_50_ds_d2h[13] = tl_ergo_hold_gen1_i;

  assign tl_ergo_hold_gen2_o = tl_s1n_50_ds_h2d[14];
  assign tl_s1n_50_ds_d2h[14] = tl_ergo_hold_gen2_i;

  assign tl_ergo_hold_gen3_o = tl_s1n_50_ds_h2d[15];
  assign tl_s1n_50_ds_d2h[15] = tl_ergo_hold_gen3_i;

  assign tl_ergo_hold_gen4_o = tl_s1n_50_ds_h2d[16];
  assign tl_s1n_50_ds_d2h[16] = tl_ergo_hold_gen4_i;

  assign tl_ergo_cdc_hazard_gen0_o = tl_s1n_50_ds_h2d[17];
  assign tl_s1n_50_ds_d2h[17] = tl_ergo_cdc_hazard_gen0_i;

  assign tl_ergo_cdc_hazard_gen1_o = tl_s1n_50_ds_h2d[18];
  assign tl_s1n_50_ds_d2h[18] = tl_ergo_cdc_hazard_gen1_i;

  assign tl_ergo_cdc_hazard_gen2_o = tl_s1n_50_ds_h2d[19];
  assign tl_s1n_50_ds_d2h[19] = tl_ergo_cdc_hazard_gen2_i;

  assign tl_ergo_cdc_hazard_gen3_o = tl_s1n_50_ds_h2d[20];
  assign tl_s1n_50_ds_d2h[20] = tl_ergo_cdc_hazard_gen3_i;

  assign tl_ergo_cdc_hazard_gen4_o = tl_s1n_50_ds_h2d[21];
  assign tl_s1n_50_ds_d2h[21] = tl_ergo_cdc_hazard_gen4_i;

  assign tl_ergo_cdc_bridge6_o = tl_s1n_50_ds_h2d[22];
  assign tl_s1n_50_ds_d2h[22] = tl_ergo_cdc_bridge6_i;

  assign tl_ergo_cdc_bridge7_o = tl_s1n_50_ds_h2d[23];
  assign tl_s1n_50_ds_d2h[23] = tl_ergo_cdc_bridge7_i;

  assign tl_ergo_cdc_bridge8_o = tl_s1n_50_ds_h2d[24];
  assign tl_s1n_50_ds_d2h[24] = tl_ergo_cdc_bridge8_i;

  assign tl_ergo_setup_gen6_o = tl_s1n_50_ds_h2d[25];
  assign tl_s1n_50_ds_d2h[25] = tl_ergo_setup_gen6_i;

  assign tl_ergo_setup_gen7_o = tl_s1n_50_ds_h2d[26];
  assign tl_s1n_50_ds_d2h[26] = tl_ergo_setup_gen7_i;

  assign tl_ergo_setup_gen8_o = tl_s1n_50_ds_h2d[27];
  assign tl_s1n_50_ds_d2h[27] = tl_ergo_setup_gen8_i;

  assign tl_ergo_hold_gen5_o = tl_s1n_50_ds_h2d[28];
  assign tl_s1n_50_ds_d2h[28] = tl_ergo_hold_gen5_i;

  assign tl_ergo_hold_gen6_o = tl_s1n_50_ds_h2d[29];
  assign tl_s1n_50_ds_d2h[29] = tl_ergo_hold_gen6_i;

  assign tl_ergo_cdc_hazard_gen5_o = tl_s1n_50_ds_h2d[30];
  assign tl_s1n_50_ds_d2h[30] = tl_ergo_cdc_hazard_gen5_i;

  assign tl_ergo_cdc_hazard_gen6_o = tl_s1n_50_ds_h2d[31];
  assign tl_s1n_50_ds_d2h[31] = tl_ergo_cdc_hazard_gen6_i;

  assign tl_uart0_o = tl_s1n_50_ds_h2d[32];
  assign tl_s1n_50_ds_d2h[32] = tl_uart0_i;

  assign tl_i2c0_o = tl_s1n_50_ds_h2d[33];
  assign tl_s1n_50_ds_d2h[33] = tl_i2c0_i;

  assign tl_gpio_o = tl_s1n_50_ds_h2d[34];
  assign tl_s1n_50_ds_d2h[34] = tl_gpio_i;

  assign tl_spi_device_o = tl_s1n_50_ds_h2d[35];
  assign tl_s1n_50_ds_d2h[35] = tl_spi_device_i;

  assign tl_rv_timer_o = tl_s1n_50_ds_h2d[36];
  assign tl_s1n_50_ds_d2h[36] = tl_rv_timer_i;

  assign tl_pwrmgr_aon_o = tl_s1n_50_ds_h2d[37];
  assign tl_s1n_50_ds_d2h[37] = tl_pwrmgr_aon_i;

  assign tl_rstmgr_aon_o = tl_s1n_50_ds_h2d[38];
  assign tl_s1n_50_ds_d2h[38] = tl_rstmgr_aon_i;

  assign tl_clkmgr_aon_o = tl_s1n_50_ds_h2d[39];
  assign tl_s1n_50_ds_d2h[39] = tl_clkmgr_aon_i;

  assign tl_pinmux_aon_o = tl_s1n_50_ds_h2d[40];
  assign tl_s1n_50_ds_d2h[40] = tl_pinmux_aon_i;

  assign tl_otp_ctrl__core_o = tl_s1n_50_ds_h2d[41];
  assign tl_s1n_50_ds_d2h[41] = tl_otp_ctrl__core_i;

  assign tl_otp_ctrl__prim_o = tl_s1n_50_ds_h2d[42];
  assign tl_s1n_50_ds_d2h[42] = tl_otp_ctrl__prim_i;

  assign tl_lc_ctrl_o = tl_s1n_50_ds_h2d[43];
  assign tl_s1n_50_ds_d2h[43] = tl_lc_ctrl_i;

  assign tl_alert_handler_o = tl_s1n_50_ds_h2d[44];
  assign tl_s1n_50_ds_d2h[44] = tl_alert_handler_i;

  assign tl_ast_o = tl_s1n_50_ds_h2d[45];
  assign tl_s1n_50_ds_d2h[45] = tl_ast_i;

  assign tl_sram_ctrl_ret_aon__ram_o = tl_s1n_50_ds_h2d[46];
  assign tl_s1n_50_ds_d2h[46] = tl_sram_ctrl_ret_aon__ram_i;

  assign tl_sram_ctrl_ret_aon__regs_o = tl_s1n_50_ds_h2d[47];
  assign tl_s1n_50_ds_d2h[47] = tl_sram_ctrl_ret_aon__regs_i;

  assign tl_aon_timer_aon_o = tl_s1n_50_ds_h2d[48];
  assign tl_s1n_50_ds_d2h[48] = tl_aon_timer_aon_i;

  assign tl_s1n_50_us_h2d = tl_main_i;
  assign tl_main_o = tl_s1n_50_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_50 = 6'd49;
    if ((tl_s1n_50_us_h2d.a_address &
         ~(ADDR_MASK_ERGO_CDC_BRIDGE0)) == ADDR_SPACE_ERGO_CDC_BRIDGE0) begin
      dev_sel_s1n_50 = 6'd0;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE1)) == ADDR_SPACE_ERGO_CDC_BRIDGE1) begin
      dev_sel_s1n_50 = 6'd1;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE2)) == ADDR_SPACE_ERGO_CDC_BRIDGE2) begin
      dev_sel_s1n_50 = 6'd2;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE3)) == ADDR_SPACE_ERGO_CDC_BRIDGE3) begin
      dev_sel_s1n_50 = 6'd3;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE4)) == ADDR_SPACE_ERGO_CDC_BRIDGE4) begin
      dev_sel_s1n_50 = 6'd4;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE5)) == ADDR_SPACE_ERGO_CDC_BRIDGE5) begin
      dev_sel_s1n_50 = 6'd5;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN0)) == ADDR_SPACE_ERGO_SETUP_GEN0) begin
      dev_sel_s1n_50 = 6'd6;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN1)) == ADDR_SPACE_ERGO_SETUP_GEN1) begin
      dev_sel_s1n_50 = 6'd7;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN2)) == ADDR_SPACE_ERGO_SETUP_GEN2) begin
      dev_sel_s1n_50 = 6'd8;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN3)) == ADDR_SPACE_ERGO_SETUP_GEN3) begin
      dev_sel_s1n_50 = 6'd9;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN4)) == ADDR_SPACE_ERGO_SETUP_GEN4) begin
      dev_sel_s1n_50 = 6'd10;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN5)) == ADDR_SPACE_ERGO_SETUP_GEN5) begin
      dev_sel_s1n_50 = 6'd11;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN0)) == ADDR_SPACE_ERGO_HOLD_GEN0) begin
      dev_sel_s1n_50 = 6'd12;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN1)) == ADDR_SPACE_ERGO_HOLD_GEN1) begin
      dev_sel_s1n_50 = 6'd13;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN2)) == ADDR_SPACE_ERGO_HOLD_GEN2) begin
      dev_sel_s1n_50 = 6'd14;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN3)) == ADDR_SPACE_ERGO_HOLD_GEN3) begin
      dev_sel_s1n_50 = 6'd15;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN4)) == ADDR_SPACE_ERGO_HOLD_GEN4) begin
      dev_sel_s1n_50 = 6'd16;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN0)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN0) begin
      dev_sel_s1n_50 = 6'd17;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN1)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN1) begin
      dev_sel_s1n_50 = 6'd18;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN2)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN2) begin
      dev_sel_s1n_50 = 6'd19;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN3)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN3) begin
      dev_sel_s1n_50 = 6'd20;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN4)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN4) begin
      dev_sel_s1n_50 = 6'd21;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE6)) == ADDR_SPACE_ERGO_CDC_BRIDGE6) begin
      dev_sel_s1n_50 = 6'd22;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE7)) == ADDR_SPACE_ERGO_CDC_BRIDGE7) begin
      dev_sel_s1n_50 = 6'd23;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_BRIDGE8)) == ADDR_SPACE_ERGO_CDC_BRIDGE8) begin
      dev_sel_s1n_50 = 6'd24;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN6)) == ADDR_SPACE_ERGO_SETUP_GEN6) begin
      dev_sel_s1n_50 = 6'd25;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN7)) == ADDR_SPACE_ERGO_SETUP_GEN7) begin
      dev_sel_s1n_50 = 6'd26;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_SETUP_GEN8)) == ADDR_SPACE_ERGO_SETUP_GEN8) begin
      dev_sel_s1n_50 = 6'd27;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN5)) == ADDR_SPACE_ERGO_HOLD_GEN5) begin
      dev_sel_s1n_50 = 6'd28;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_HOLD_GEN6)) == ADDR_SPACE_ERGO_HOLD_GEN6) begin
      dev_sel_s1n_50 = 6'd29;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN5)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN5) begin
      dev_sel_s1n_50 = 6'd30;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ERGO_CDC_HAZARD_GEN6)) == ADDR_SPACE_ERGO_CDC_HAZARD_GEN6) begin
      dev_sel_s1n_50 = 6'd31;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_UART0)) == ADDR_SPACE_UART0) begin
      dev_sel_s1n_50 = 6'd32;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_I2C0)) == ADDR_SPACE_I2C0) begin
      dev_sel_s1n_50 = 6'd33;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_GPIO)) == ADDR_SPACE_GPIO) begin
      dev_sel_s1n_50 = 6'd34;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SPI_DEVICE)) == ADDR_SPACE_SPI_DEVICE) begin
      dev_sel_s1n_50 = 6'd35;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RV_TIMER)) == ADDR_SPACE_RV_TIMER) begin
      dev_sel_s1n_50 = 6'd36;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_PWRMGR_AON)) == ADDR_SPACE_PWRMGR_AON) begin
      dev_sel_s1n_50 = 6'd37;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_RSTMGR_AON)) == ADDR_SPACE_RSTMGR_AON) begin
      dev_sel_s1n_50 = 6'd38;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_CLKMGR_AON)) == ADDR_SPACE_CLKMGR_AON) begin
      dev_sel_s1n_50 = 6'd39;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_PINMUX_AON)) == ADDR_SPACE_PINMUX_AON) begin
      dev_sel_s1n_50 = 6'd40;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_OTP_CTRL__CORE)) == ADDR_SPACE_OTP_CTRL__CORE) begin
      dev_sel_s1n_50 = 6'd41;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_OTP_CTRL__PRIM)) == ADDR_SPACE_OTP_CTRL__PRIM) begin
      dev_sel_s1n_50 = 6'd42;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_LC_CTRL)) == ADDR_SPACE_LC_CTRL) begin
      dev_sel_s1n_50 = 6'd43;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_ALERT_HANDLER)) == ADDR_SPACE_ALERT_HANDLER) begin
      dev_sel_s1n_50 = 6'd44;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_AST)) == ADDR_SPACE_AST) begin
      dev_sel_s1n_50 = 6'd45;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_RET_AON__RAM)) == ADDR_SPACE_SRAM_CTRL_RET_AON__RAM) begin
      dev_sel_s1n_50 = 6'd46;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_SRAM_CTRL_RET_AON__REGS)) == ADDR_SPACE_SRAM_CTRL_RET_AON__REGS) begin
      dev_sel_s1n_50 = 6'd47;

    end else if ((tl_s1n_50_us_h2d.a_address &
                  ~(ADDR_MASK_AON_TIMER_AON)) == ADDR_SPACE_AON_TIMER_AON) begin
      dev_sel_s1n_50 = 6'd48;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (196'h0),
    .DRspDepth (196'h0),
    .N         (49)
  ) u_s1n_50 (
    .clk_i        (clk_peri_i),
    .rst_ni       (rst_peri_ni),
    .tl_h_i       (tl_s1n_50_us_h2d),
    .tl_h_o       (tl_s1n_50_us_d2h),
    .tl_d_o       (tl_s1n_50_ds_h2d),
    .tl_d_i       (tl_s1n_50_ds_d2h),
    .dev_select_i (dev_sel_s1n_50)
  );

endmodule
