// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_peri dut();

`DRIVE_CLK(clk_peri_i)

initial force dut.clk_peri_i = clk_peri_i;

// TODO, all resets tie together
initial force dut.rst_peri_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(main, dut, clk_peri_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge2, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge3, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge4, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge5, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen2, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen3, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen4, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen5, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen2, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen3, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen4, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen1, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen2, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen3, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen4, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge6, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge7, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_bridge8, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen6, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen7, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_setup_gen8, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen5, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_hold_gen6, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen5, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ergo_cdc_hazard_gen6, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(uart0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(i2c0, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(gpio, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(spi_device, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_timer, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(pwrmgr_aon, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(rstmgr_aon, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(clkmgr_aon, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(pinmux_aon, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(otp_ctrl__core, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(otp_ctrl__prim, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(lc_ctrl, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(alert_handler, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl_ret_aon__regs, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl_ret_aon__ram, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(aon_timer_aon, dut, clk_peri_i, rst_n)
`CONNECT_TL_DEVICE_IF(ast, dut, clk_peri_i, rst_n)
