#!/usr/bin/env python3
# Copyright Gargantuan5k, 2026.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
"""Generate an SDC (timing constraints) file for top_earlgrey from its
clock-tree source of truth (top_earlgrey.hjson, via clocks.py's
ClockConfig) and clkmgr's divider-instantiation topology (a fixed topgen
template convention: every derived clock <name> is produced by an
instance named u_no_scan_<name>_div inside u_clkmgr_aon, with a clk_o
output pin — verified against hw/top_earlgrey/ip_autogen/clkmgr/rtl/
clkmgr.sv and the synthesized netlist).

Scope: internal clock-domain timing only. Top-level IO/pad ports (mio_*,
dio_*, ast_*, flash_*, otp_*, scan_*, ...) are intentionally left
unconstrained — none of this benchmark's injected violations (see
hw/top_earlgrey/data/ergo_manifest.yaml) touch chip-boundary ports, all
are IP-internal, and this repo has no real package/board timing spec to
derive input/output delays from. Modeling fictitious IO timing would be
worse than omitting it.

Clock grouping: clocks derived from the same master oscillator are kept
in one synchronous group (via create_generated_clock's -source/-divide_by
relationship), so the deliberate hold/CDC-hazard violations in
ergo_hold_gen/ergo_cdc_hazard_gen — which cross between a master and its
own derived clock — are actually measured. Clocks from *different*
families are marked mutually asynchronous (set_clock_groups), matching
every genuinely independent-oscillator crossing in this design, including
ergo_cdc_bridge's crossings, which are deliberately reference-correct
(prim_fifo_async + prim_sync_reqack) and must NOT be flagged as ordinary
synchronous setup/hold violations.

This file is regenerated every run (like the netlist and area.rpt) rather
than hand-maintained — it depends only on values already declared
elsewhere (top_earlgrey.hjson's clock freqs, clkmgr's fixed divider
naming), so hand-maintaining a second copy would just be another place
for those to drift apart.

Usage:
  util/nebula/gen_sdc.py                # writes hw/top_earlgrey/syn_out/top_earlgrey.sdc
  util/nebula/gen_sdc.py --out FILE
"""
import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from clocks import ClockConfig  # noqa: E402

DEFAULT_HJSON = REPO_ROOT / "hw/top_earlgrey/data/top_earlgrey.hjson"
DEFAULT_OUT = REPO_ROOT / "hw/top_earlgrey/syn_out/top_earlgrey.sdc"
CLKMGR_INST = "u_clkmgr_aon"

HEADER = """\
# Auto-generated by util/nebula/gen_sdc.py -- do not hand-edit.
# Source of truth: hw/top_earlgrey/data/top_earlgrey.hjson (clock freqs)
#                   hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv (divider topology)
#
# Scope: internal clock-domain timing only. Top-level IO/pad ports (mio_*,
# dio_*, ast_*, flash_*, otp_*, scan_*, ...) are intentionally left
# unconstrained -- none of this benchmark's injected violations (see
# hw/top_earlgrey/data/ergo_manifest.yaml) touch chip-boundary ports, all
# are IP-internal, and this repo has no real package/board timing spec to
# derive input/output delays from. Modeling fictitious IO timing would be
# worse than omitting it.
#
# Clock family grouping: clocks derived from the same master oscillator
# are analyzed together (so the deliberate hold/CDC-hazard violations in
# ergo_hold_gen/ergo_cdc_hazard_gen, which cross between a master and its
# own derived clock, are actually measured -- they're a real synchronous
# generated-clock relationship, not noise). Clocks from *different*
# families are marked asynchronous below, matching every genuinely
# independent-oscillator crossing in this design -- including
# ergo_cdc_bridge's crossings, which are deliberately reference-correct
# (prim_fifo_async + prim_sync_reqack) and must NOT be flagged as
# synchronous setup/hold violations.
"""


def divider_pin(name: str) -> str:
    return f"{CLKMGR_INST}/u_no_scan_{name}_div/clk_o"


def freq_to_period_ns(freq_hz: int) -> float:
    return 1e9 / freq_hz


def build_sdc(cfg: ClockConfig) -> str:
    lines = [HEADER, "## Master clocks"]
    for name in sorted(cfg.srcs):
        period = freq_to_period_ns(cfg.srcs[name]["freq"])
        lines.append(
            f"create_clock -name {name} -period {period:.3f} "
            f"[get_ports clk_{name}_i]"
        )

    lines += ["", "## Generated (divided) clocks"]
    for name in sorted(cfg.derived):
        d = cfg.derived[name]
        lines.append(
            f"create_generated_clock -name {name} "
            f"-source [get_ports clk_{d['src']}_i] -divide_by {d['div']} "
            f"[get_pins {divider_pin(name)}]"
        )

    families = {name: [name] for name in cfg.srcs}
    for name, d in cfg.derived.items():
        families[d["src"]].append(name)

    lines += ["", "## Clock groups: asynchronous across independent oscillators,",
              "## synchronous (via the generated-clock relationships above) within",
              "set_clock_groups -asynchronous \\"]
    group_lines = [
        f"  -group {{{' '.join(sorted(families[master]))}}}"
        for master in sorted(families)
    ]
    lines.append(" \\\n".join(group_lines))
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--hjson", default=str(DEFAULT_HJSON))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    cfg = ClockConfig(args.hjson)
    sdc = build_sdc(cfg)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sdc)
    n_groups = len(cfg.srcs)
    print(
        f"wrote {out_path} "
        f"({len(cfg.srcs)} master clocks, {len(cfg.derived)} generated clocks, "
        f"{n_groups} clock groups)"
    )


if __name__ == "__main__":
    main()
