// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ergo_cdc_bridge_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } ergo_cdc_bridge_reg2hw_data_in_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } empty;
    struct packed {
      logic        d;
      logic        de;
    } full;
  } ergo_cdc_bridge_hw2reg_fifo_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } ergo_cdc_bridge_hw2reg_pop_count_reg_t;

  // Register -> HW type
  typedef struct packed {
    ergo_cdc_bridge_reg2hw_data_in_reg_t data_in; // [8:0]
  } ergo_cdc_bridge_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    ergo_cdc_bridge_hw2reg_fifo_status_reg_t fifo_status; // [36:33]
    ergo_cdc_bridge_hw2reg_pop_count_reg_t pop_count; // [32:0]
  } ergo_cdc_bridge_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ERGO_CDC_BRIDGE_DATA_IN_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] ERGO_CDC_BRIDGE_FIFO_STATUS_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] ERGO_CDC_BRIDGE_POP_COUNT_OFFSET = 4'h 8;

  // Reset values for hwext registers and their fields
  parameter logic [7:0] ERGO_CDC_BRIDGE_DATA_IN_RESVAL = 8'h 0;

  // Register index
  typedef enum int {
    ERGO_CDC_BRIDGE_DATA_IN,
    ERGO_CDC_BRIDGE_FIFO_STATUS,
    ERGO_CDC_BRIDGE_POP_COUNT
  } ergo_cdc_bridge_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ERGO_CDC_BRIDGE_PERMIT [3] = '{
    4'b 0001, // index[0] ERGO_CDC_BRIDGE_DATA_IN
    4'b 0001, // index[1] ERGO_CDC_BRIDGE_FIFO_STATUS
    4'b 1111  // index[2] ERGO_CDC_BRIDGE_POP_COUNT
  };

endpackage
