# Auto-generated by util/nebula/gen_sdc.py -- do not hand-edit.
# Source of truth: hw/top_earlgrey/data/top_earlgrey.hjson (clock freqs)
#                   hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv (divider topology)
#
# Scope: internal clock-domain timing only. Top-level IO/pad ports (mio_*,
# dio_*, ast_*, flash_*, otp_*, scan_*, ...) are intentionally left
# unconstrained -- none of this benchmark's injected violations (see
# hw/top_earlgrey/data/ergo_manifest.yaml) touch chip-boundary ports, all
# are IP-internal, and this repo has no real package/board timing spec to
# derive input/output delays from. Modeling fictitious IO timing would be
# worse than omitting it.
#
# Clock family grouping: clocks derived from the same master oscillator
# are analyzed together (so the deliberate hold/CDC-hazard violations in
# ergo_hold_gen/ergo_cdc_hazard_gen, which cross between a master and its
# own derived clock, are actually measured -- they're a real synchronous
# generated-clock relationship, not noise). Clocks from *different*
# families are marked asynchronous below, matching every genuinely
# independent-oscillator crossing in this design -- including
# ergo_cdc_bridge's crossings, which are deliberately reference-correct
# (prim_fifo_async + prim_sync_reqack) and must NOT be flagged as
# synchronous setup/hold violations.

## Master clocks
create_clock -name aon -period 5000.000 [get_ports clk_aon_i]
create_clock -name exp -period 13.889 [get_ports clk_exp_i]
create_clock -name exp2 -period 16.667 [get_ports clk_exp2_i]
create_clock -name io -period 10.417 [get_ports clk_io_i]
create_clock -name main -period 10.000 [get_ports clk_main_i]
create_clock -name usb -period 20.833 [get_ports clk_usb_i]

## Generated (divided) clocks
create_generated_clock -name exp2_div2 -source [get_ports clk_exp2_i] -divide_by 2 [get_pins u_clkmgr_aon/u_no_scan_exp2_div2_div/clk_o]
create_generated_clock -name exp2_div6 -source [get_ports clk_exp2_i] -divide_by 6 [get_pins u_clkmgr_aon/u_no_scan_exp2_div6_div/clk_o]
create_generated_clock -name exp_div2 -source [get_ports clk_exp_i] -divide_by 2 [get_pins u_clkmgr_aon/u_no_scan_exp_div2_div/clk_o]
create_generated_clock -name exp_div8 -source [get_ports clk_exp_i] -divide_by 8 [get_pins u_clkmgr_aon/u_no_scan_exp_div8_div/clk_o]
create_generated_clock -name io_div2 -source [get_ports clk_io_i] -divide_by 2 [get_pins u_clkmgr_aon/u_no_scan_io_div2_div/clk_o]
create_generated_clock -name io_div4 -source [get_ports clk_io_i] -divide_by 4 [get_pins u_clkmgr_aon/u_no_scan_io_div4_div/clk_o]
create_generated_clock -name main_div10 -source [get_ports clk_main_i] -divide_by 10 [get_pins u_clkmgr_aon/u_no_scan_main_div10_div/clk_o]
create_generated_clock -name main_div2 -source [get_ports clk_main_i] -divide_by 2 [get_pins u_clkmgr_aon/u_no_scan_main_div2_div/clk_o]
create_generated_clock -name usb_div4 -source [get_ports clk_usb_i] -divide_by 4 [get_pins u_clkmgr_aon/u_no_scan_usb_div4_div/clk_o]

## Clock groups: asynchronous across independent oscillators,
## synchronous (via the generated-clock relationships above) within
set_clock_groups -asynchronous \
  -group {aon} \
  -group {exp exp_div2 exp_div8} \
  -group {exp2 exp2_div2 exp2_div6} \
  -group {io io_div2 io_div4} \
  -group {main main_div10 main_div2} \
  -group {usb usb_div4}

