// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ergo_cdc_hazard_gen_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } ergo_cdc_hazard_gen_hw2reg_mismatch_count_reg_t;

  // HW -> register type
  typedef struct packed {
    ergo_cdc_hazard_gen_hw2reg_mismatch_count_reg_t mismatch_count; // [32:0]
  } ergo_cdc_hazard_gen_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ERGO_CDC_HAZARD_GEN_MISMATCH_COUNT_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    ERGO_CDC_HAZARD_GEN_MISMATCH_COUNT
  } ergo_cdc_hazard_gen_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ERGO_CDC_HAZARD_GEN_PERMIT [1] = '{
    4'b 1111  // index[0] ERGO_CDC_HAZARD_GEN_MISMATCH_COUNT
  };

endpackage
