// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ergo_hold_gen_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } ergo_hold_gen_reg2hw_seed_reg_t;

  typedef struct packed {
    logic [7:0]  d;
    logic        de;
  } ergo_hold_gen_hw2reg_captured_reg_t;

  // Register -> HW type
  typedef struct packed {
    ergo_hold_gen_reg2hw_seed_reg_t seed; // [8:0]
  } ergo_hold_gen_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    ergo_hold_gen_hw2reg_captured_reg_t captured; // [8:0]
  } ergo_hold_gen_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ERGO_HOLD_GEN_SEED_OFFSET = 3'h 0;
  parameter logic [BlockAw-1:0] ERGO_HOLD_GEN_CAPTURED_OFFSET = 3'h 4;

  // Reset values for hwext registers and their fields
  parameter logic [7:0] ERGO_HOLD_GEN_SEED_RESVAL = 8'h 0;

  // Register index
  typedef enum int {
    ERGO_HOLD_GEN_SEED,
    ERGO_HOLD_GEN_CAPTURED
  } ergo_hold_gen_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ERGO_HOLD_GEN_PERMIT [2] = '{
    4'b 0001, // index[0] ERGO_HOLD_GEN_SEED
    4'b 0001  // index[1] ERGO_HOLD_GEN_CAPTURED
  };

endpackage
