// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h41200000, 32'h4120000f}
    }},
    '{"rv_dm__mem", '{
        '{32'h00010000, 32'h00010fff}
    }},
    '{"rom_ctrl__rom", '{
        '{32'h00008000, 32'h0000ffff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h411e0000, 32'h411e007f}
    }},
    '{"spi_host0", '{
        '{32'h40300000, 32'h4030003f}
    }},
    '{"flash_ctrl__core", '{
        '{32'h41000000, 32'h410001ff}
    }},
    '{"flash_ctrl__prim", '{
        '{32'h41008000, 32'h4100807f}
    }},
    '{"flash_ctrl__mem", '{
        '{32'h20000000, 32'h200fffff}
    }},
    '{"kmac", '{
        '{32'h41120000, 32'h41120fff}
    }},
    '{"entropy_src", '{
        '{32'h41160000, 32'h411600ff}
    }},
    '{"csrng", '{
        '{32'h41150000, 32'h4115007f}
    }},
    '{"edn0", '{
        '{32'h41170000, 32'h4117007f}
    }},
    '{"rv_plic", '{
        '{32'h48000000, 32'h4fffffff}
    }},
    '{"keymgr", '{
        '{32'h41140000, 32'h411400ff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h411f0000, 32'h411f00ff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h411c0000, 32'h411c003f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1001ffff}
    }},
    '{"ergo_cdc_bridge0", '{
        '{32'h40060000, 32'h4006000f}
    }},
    '{"ergo_cdc_bridge1", '{
        '{32'h40070000, 32'h4007000f}
    }},
    '{"ergo_cdc_bridge2", '{
        '{32'h400b0000, 32'h400b000f}
    }},
    '{"ergo_cdc_bridge3", '{
        '{32'h400c0000, 32'h400c000f}
    }},
    '{"ergo_cdc_bridge4", '{
        '{32'h400d0000, 32'h400d000f}
    }},
    '{"ergo_cdc_bridge5", '{
        '{32'h40110000, 32'h4011000f}
    }},
    '{"ergo_setup_gen0", '{
        '{32'h40120000, 32'h40120007}
    }},
    '{"ergo_setup_gen1", '{
        '{32'h40160000, 32'h40160007}
    }},
    '{"ergo_setup_gen2", '{
        '{32'h40170000, 32'h40170007}
    }},
    '{"ergo_setup_gen3", '{
        '{32'h40180000, 32'h40180007}
    }},
    '{"ergo_setup_gen4", '{
        '{32'h40190000, 32'h40190007}
    }},
    '{"ergo_setup_gen5", '{
        '{32'h401a0000, 32'h401a0007}
    }},
    '{"ergo_hold_gen0", '{
        '{32'h401b0000, 32'h401b0007}
    }},
    '{"ergo_hold_gen1", '{
        '{32'h401c0000, 32'h401c0007}
    }},
    '{"ergo_hold_gen2", '{
        '{32'h401d0000, 32'h401d0007}
    }},
    '{"ergo_hold_gen3", '{
        '{32'h401e0000, 32'h401e0007}
    }},
    '{"ergo_hold_gen4", '{
        '{32'h401f0000, 32'h401f0007}
    }},
    '{"ergo_cdc_hazard_gen0", '{
        '{32'h40200000, 32'h40200003}
    }},
    '{"ergo_cdc_hazard_gen1", '{
        '{32'h40210000, 32'h40210003}
    }},
    '{"ergo_cdc_hazard_gen2", '{
        '{32'h40220000, 32'h40220003}
    }},
    '{"ergo_cdc_hazard_gen3", '{
        '{32'h40230000, 32'h40230003}
    }},
    '{"ergo_cdc_hazard_gen4", '{
        '{32'h40240000, 32'h40240003}
    }},
    '{"ergo_cdc_bridge6", '{
        '{32'h40250000, 32'h4025000f}
    }},
    '{"ergo_cdc_bridge7", '{
        '{32'h40260000, 32'h4026000f}
    }},
    '{"ergo_cdc_bridge8", '{
        '{32'h40270000, 32'h4027000f}
    }},
    '{"ergo_setup_gen6", '{
        '{32'h40280000, 32'h40280007}
    }},
    '{"ergo_setup_gen7", '{
        '{32'h40290000, 32'h40290007}
    }},
    '{"ergo_setup_gen8", '{
        '{32'h402a0000, 32'h402a0007}
    }},
    '{"ergo_hold_gen5", '{
        '{32'h402b0000, 32'h402b0007}
    }},
    '{"ergo_hold_gen6", '{
        '{32'h402c0000, 32'h402c0007}
    }},
    '{"ergo_cdc_hazard_gen5", '{
        '{32'h402d0000, 32'h402d0003}
    }},
    '{"ergo_cdc_hazard_gen6", '{
        '{32'h402e0000, 32'h402e0003}
    }},
    '{"uart0", '{
        '{32'h40000000, 32'h4000003f}
    }},
    '{"i2c0", '{
        '{32'h40080000, 32'h4008007f}
    }},
    '{"gpio", '{
        '{32'h40040000, 32'h4004003f}
    }},
    '{"spi_device", '{
        '{32'h40050000, 32'h40051fff}
    }},
    '{"rv_timer", '{
        '{32'h40100000, 32'h401001ff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h40400000, 32'h4040007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h40410000, 32'h4041007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h40420000, 32'h4042007f}
    }},
    '{"pinmux_aon", '{
        '{32'h40460000, 32'h404607ff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h40130000, 32'h40130fff}
    }},
    '{"otp_ctrl__prim", '{
        '{32'h40138000, 32'h4013801f}
    }},
    '{"lc_ctrl", '{
        '{32'h40140000, 32'h401400ff}
    }},
    '{"alert_handler", '{
        '{32'h40150000, 32'h401507ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h40500000, 32'h4050003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h40600000, 32'h40600fff}
    }},
    '{"aon_timer_aon", '{
        '{32'h40470000, 32'h4047003f}
    }},
    '{"ast", '{
        '{32'h40480000, 32'h404803ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rom_ctrl__rom",
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "flash_ctrl__mem"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "ergo_cdc_bridge0",
        "ergo_cdc_bridge1",
        "ergo_cdc_bridge2",
        "ergo_cdc_bridge3",
        "ergo_cdc_bridge4",
        "ergo_cdc_bridge5",
        "ergo_setup_gen0",
        "ergo_setup_gen1",
        "ergo_setup_gen2",
        "ergo_setup_gen3",
        "ergo_setup_gen4",
        "ergo_setup_gen5",
        "ergo_hold_gen0",
        "ergo_hold_gen1",
        "ergo_hold_gen2",
        "ergo_hold_gen3",
        "ergo_hold_gen4",
        "ergo_cdc_hazard_gen0",
        "ergo_cdc_hazard_gen1",
        "ergo_cdc_hazard_gen2",
        "ergo_cdc_hazard_gen3",
        "ergo_cdc_hazard_gen4",
        "ergo_cdc_bridge6",
        "ergo_cdc_bridge7",
        "ergo_cdc_bridge8",
        "ergo_setup_gen6",
        "ergo_setup_gen7",
        "ergo_setup_gen8",
        "ergo_hold_gen5",
        "ergo_hold_gen6",
        "ergo_cdc_hazard_gen5",
        "ergo_cdc_hazard_gen6",
        "uart0",
        "i2c0",
        "gpio",
        "spi_device",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_ctrl__prim",
        "lc_ctrl",
        "alert_handler",
        "ast",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "spi_host0",
        "flash_ctrl__core",
        "flash_ctrl__prim",
        "flash_ctrl__mem",
        "entropy_src",
        "csrng",
        "edn0",
        "rv_plic",
        "keymgr",
        "kmac",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "ergo_cdc_bridge0",
        "ergo_cdc_bridge1",
        "ergo_cdc_bridge2",
        "ergo_cdc_bridge3",
        "ergo_cdc_bridge4",
        "ergo_cdc_bridge5",
        "ergo_setup_gen0",
        "ergo_setup_gen1",
        "ergo_setup_gen2",
        "ergo_setup_gen3",
        "ergo_setup_gen4",
        "ergo_setup_gen5",
        "ergo_hold_gen0",
        "ergo_hold_gen1",
        "ergo_hold_gen2",
        "ergo_hold_gen3",
        "ergo_hold_gen4",
        "ergo_cdc_hazard_gen0",
        "ergo_cdc_hazard_gen1",
        "ergo_cdc_hazard_gen2",
        "ergo_cdc_hazard_gen3",
        "ergo_cdc_hazard_gen4",
        "ergo_cdc_bridge6",
        "ergo_cdc_bridge7",
        "ergo_cdc_bridge8",
        "ergo_setup_gen6",
        "ergo_setup_gen7",
        "ergo_setup_gen8",
        "ergo_hold_gen5",
        "ergo_hold_gen6",
        "ergo_cdc_hazard_gen5",
        "ergo_cdc_hazard_gen6",
        "uart0",
        "i2c0",
        "gpio",
        "spi_device",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_ctrl__prim",
        "lc_ctrl",
        "alert_handler",
        "ast",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "spi_host0",
        "flash_ctrl__core",
        "flash_ctrl__prim",
        "flash_ctrl__mem",
        "entropy_src",
        "csrng",
        "edn0",
        "rv_plic",
        "keymgr",
        "kmac",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg"}}
};
