// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ergo_setup_gen_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [15:0] q;
    logic        qe;
  } ergo_setup_gen_reg2hw_operand_in_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } ergo_setup_gen_hw2reg_result_reg_t;

  // Register -> HW type
  typedef struct packed {
    ergo_setup_gen_reg2hw_operand_in_reg_t operand_in; // [16:0]
  } ergo_setup_gen_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    ergo_setup_gen_hw2reg_result_reg_t result; // [32:0]
  } ergo_setup_gen_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ERGO_SETUP_GEN_OPERAND_IN_OFFSET = 3'h 0;
  parameter logic [BlockAw-1:0] ERGO_SETUP_GEN_RESULT_OFFSET = 3'h 4;

  // Reset values for hwext registers and their fields
  parameter logic [15:0] ERGO_SETUP_GEN_OPERAND_IN_RESVAL = 16'h 0;

  // Register index
  typedef enum int {
    ERGO_SETUP_GEN_OPERAND_IN,
    ERGO_SETUP_GEN_RESULT
  } ergo_setup_gen_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ERGO_SETUP_GEN_PERMIT [2] = '{
    4'b 0011, // index[0] ERGO_SETUP_GEN_OPERAND_IN
    4'b 1111  // index[1] ERGO_SETUP_GEN_RESULT
  };

endpackage
